In [1]:
import torch 
import numpy as np

In [12]:
# DELETE THIS LATER 

x_rand = np.random.uniform(0,1.0,size=(10,5))

x_var = np.var(x_rand, axis=1)
print(f"The variance of x_rand is: {x_var}")

The variance of x_rand is: [0.05711822 0.10322172 0.1506353  0.03605849 0.09888216 0.0182294
 0.05326188 0.07411058 0.10163028 0.02736652]


In [3]:
data = [[1,2],[3,4]]
x_data = torch.tensor(data)

In [4]:
np_array = np.array(data)
x_data = torch.from_numpy(np_array)

In [14]:
x_ones = torch.ones_like(x_data, dtype=torch.float64)
print(f"Ones tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float64)
print(f"Rand Tensor: \n {x_rand}")

Ones tensor: 
 tensor([[1., 1.],
        [1., 1.]], dtype=torch.float64) 

Rand Tensor: 
 tensor([[0.3670, 0.5177],
        [0.0710, 0.7463]], dtype=torch.float64)


In [19]:
shape = (3,3)
    
x_ones = torch.ones(shape)
x_rand = torch.rand(shape)
print(f"Ones tensor of shape: {shape}\n {x_ones}\n'")
print(f"Random tensor of shape: {shape}\n {x_rand}\n'")

print(x_rand.shape)

Ones tensor of shape: (3, 3)
 tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
'
Random tensor of shape: (3, 3)
 tensor([[0.0960, 0.5680, 0.6362],
        [0.9714, 0.2467, 0.1662],
        [0.8112, 0.8573, 0.6394]])
'
torch.Size([3, 3])


In [20]:
if torch.cuda.is_available():
    device = "cuda" 

In [34]:
tensor = torch.rand(size=(3,4))
tensor=tensor.to(device)
print(tensor)

tensor([[0.4057, 0.7036, 0.2524, 0.1416],
        [0.3153, 0.4806, 0.8902, 0.5878],
        [0.0317, 0.6670, 0.2629, 0.3278]], device='cuda:0')


In [35]:
print(f"Printing the last column: {tensor[...,-1]}")
print(f"Printing the first colum: {tensor[:,0]}")

Printing the last column: tensor([0.1416, 0.5878, 0.3278], device='cuda:0')
Printing the first colum: tensor([0.4057, 0.3153, 0.0317], device='cuda:0')


In [36]:
print(f"Shape of X:{x_rand.shape}")
print(f"Shape of Tensor:{tensor.shape}")

Shape of X:torch.Size([3, 3])
Shape of Tensor:torch.Size([3, 4])


In [42]:
x_rand=x_rand.to(device)
t1 = torch.cat([tensor,x_rand], dim=1)
t1 = t1.to(device)

### Concatenating tensors

The `torch.cat` function can take in multiple tensors and concatenate them. An important parameter to this function is the `dim` param. It tells the function along which dimension to concatenate the tensors. Tensors have 0-based indexing, so `dim=1` means concatenating the columns, but for this an important condition is that the number of rows in this case, must be equal. 

That is, if concatenating two tensors `t1` and `t2` using `dim=1`, this is what the shape of the tensors should be like: `t1[x][y]` and `t2[x][z]`.


In [40]:
print(t1)

tensor([[0.4057, 0.7036, 0.2524, 0.1416, 0.0960, 0.5680, 0.6362],
        [0.3153, 0.4806, 0.8902, 0.5878, 0.9714, 0.2467, 0.1662],
        [0.0317, 0.6670, 0.2629, 0.3278, 0.8112, 0.8573, 0.6394]],
       device='cuda:0')


In [44]:
t2 = torch.rand_like(t1)
t2 = t2.to(device)

tensor([[0.4760, 0.9082, 0.8475, 0.2650, 0.5413, 0.8369, 0.6379],
        [0.9708, 0.6364, 0.7796, 0.0241, 0.0724, 0.1716, 0.0875],
        [0.1175, 0.2642, 0.1723, 0.3901, 0.5079, 0.1674, 0.9669]],
       device='cuda:0')


In [48]:
t_stack = torch.stack([t1,t2])
t_stack = t_stack.to(device)

In [50]:
print(t_stack.shape)

torch.Size([2, 3, 7])
